import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";


const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Trade Phere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <div className="max-w-screen overflow-hidden relative">
          {/* <Navbar /> */}
          {children}
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
